# Default values for client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

container:
  name: client

image:
  name: foxt451/mcsvc-client
  tag: latest

service:
  ports:
    - name: app
      port: 80
      containerPort: 80

ingress:
  path: "/"
  port: app
