apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres:14.1-alpine3.15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-auth-config
            - secretRef:
                name: postgres-auth-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-auth
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
      volumes:
        - name: postgredb-auth
          persistentVolumeClaim:
            claimName: postgres-auth-volume-claim
