{{- define "common.secret.tpl" -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.fullname" . }}-secret
data:
  {{- range $key, $value := .Values.secret.data }}
    {{ $key }}: |-
{{ $value | indent 6 }}
  {{- end }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
    {{ $key }}: |-
{{ $value | indent 6 }}
  {{- end }}
{{- end -}}

{{- define "common.secret" -}}
{{- include "common.util.merge" (append . "common.secret.tpl") -}}
{{- end -}}