{{- define "common.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{ end }}

{{- define "common.service" -}}
{{- include "common.util.merge" (append . "common.service.tpl") -}}
{{- end -}}