apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-service
  template:
    metadata:
      labels:
        app: tasks-service
    spec:
      containers:
        - name: tasks-service
          image: foxt451/mcsvc_tasks_service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: tasks-secret
          volumeMounts:
            - mountPath: /app/build/helpers/keys
              name: tasks-enckeys
              readOnly: true
      initContainers:
        - name: run-migrations-tasks
          image: foxt451/tasks-migrations:latest
          imagePullPolicy: Always
          command:
            [
              "migrate",
              "-path",
              "/migrations",
              "-database",
              "$(TASK_DB_URL)",
              "up",
            ]
          envFrom:
            - secretRef:
                name: tasks-secret
      volumes:
        - name: tasks-enckeys
          secret:
            secretName: tasks-enckeys-secret
            items:
              - key: PUBLIC_KEY
                path: public.txt
