# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: tasks-enckeys-secret
# stringData:
#  PUBLIC_KEY: | 
#   -----BEGIN PUBLIC KEY-----
#   MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBsMLYcPI7LpJvUt34Jl83aGH18lN
#   Y0AkCUm4AqovpMcFHOYD9+od7/lorsCUB7R+dHsIu8VD+3s5P5r0DZSJ3w==
#   -----END PUBLIC KEY-----