# Default values for tasks-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  fullnameOverride: postgres-tasks
  postgresqlDatabase: "tasks"
  postgresqlUsername: "demo"
  postgresqlPassword: "demo"
  persistence:
    size: 5Gi
    mountPath: /var/lib/postgresql/data

container:
  name: tasks

image:
  name: foxt451/mcsvc_tasks_service
  tag: latest

migrations:
  image:
    name: foxt451/tasks-migrations
    tag: latest
  dbEnvName: "TASK_DB_URL"

service:
  ports:
    - name: app
      port: 3000
      containerPort: 3000

ingress:
  path: "/api/tasks/v1(/|$)(.*)"
  port: app
  pathRewrite: "/$2"

secret:
  stringData:
    TASK_DB_URL: "postgresql://demo:demo@postgres-tasks:5432/tasks?sslmode=disable"
    PUBLIC_KEY: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBsMLYcPI7LpJvUt34Jl83aGH18lN
      Y0AkCUm4AqovpMcFHOYD9+od7/lorsCUB7R+dHsIu8VD+3s5P5r0DZSJ3w==
      -----END PUBLIC KEY-----

secretMounts:
  mountPath: /app/build/helpers/keys
  paths:
    PUBLIC_KEY: public.txt