apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  BROKER_URL: kafka:9092
  EMAIL_QUEUE_TOPIC: email-queue
  AUTH_SVC_URL: http://auth-service:3000
  TASK_QUEUE_TOPIC: task-updates
